### ISSUE TITLE
插件在 Nukkit git-65062f5 中开启报错

### ISSUE THREAD

**Issue by XieXiLin158** [CardinalDevLab/NukkitQQSync#2]
版本:Nukkit git-65062f5 「」API 版本 1.0.11 的 Minecraft: BE v1.16.200 (协 议版本 422)
报错:
[36m19:59:50[m [[1;31mERROR[m] Throwing
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access class kotlin.collections.ArraysUtilJVM from class kotlin.collections.ArraysKt___ArraysKt
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:743) [nukkit.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:732) [nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:575) [nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access class kotlin.collections.ArraysUtilJVM from class kotlin.collections.ArraysKt___ArraysKt
        at kotlin.collections.ArraysKt___ArraysKt.asList(_Arrays.kt:13005) ~[?:?]
        at kotlin.collections.CollectionsKt__CollectionsKt.listOf(Collections.kt:77) ~[?:?]
        at kotlin.reflect.jvm.internal.impl.descriptors.runtime.structure.ReflectClassUtilKt.<clinit>(reflectClassUtil.kt:33) ~[?:?]
        at kotlin.reflect.jvm.internal.RuntimeTypeMapper.mapJvmClassToKotlinClassId(RuntimeTypeMapper.kt:273) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl.getClassId(KClassImpl.kt:186) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl.access$getClassId$p(KClassImpl.kt:44) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:49) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$nestedClasses$2.invoke(KClassImpl.kt:100) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$nestedClasses$2.invoke(KClassImpl.kt:47) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?]        at kotlin.reflect.jvm.internal.KClassImpl$Data.getNestedClasses(KClassImpl.kt) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl.getNestedClasses(KClassImpl.kt:240) ~[?:?]
        at kotlin.reflect.full.KClasses.getCompanionObject(KClasses.kt:51) ~[?:?]
        at kotlin.reflect.full.KClasses.getCompanionObjectInstance(KClasses.kt:61) ~[?:?]
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18) ~[?:?]
        at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt:34) ~[?:?]
        at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt) ~[?:?]
        at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:50) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261]
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18) ~[?:?]
        at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt:34) ~[?:?]
        at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt) ~[?:?]
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116) ~[?:?]
        at dev.cardinaldevlab.NukkitQQ.onEnable(NukkitQQ.java:227) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit.jar:?]
        ... 4 more

config里面nogui_support无论打开还是关闭都报一样的错
请求issue

**Comment by ExusiaiMoe** [comment]
请发送一下执行
`java -version`
后的输出

**Comment by XieXiLin158** [comment]
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**Comment by ExusiaiMoe** [comment]
新版的mirai不支持openjdk
请更换openjdk
